### ISSUE TITLE
Can't install the package

### ISSUE THREAD

**Issue by hubshi** [Community-PIO-CH32V/ch32-pio-projects#5] opened 2024-01-31 17:11 UTC
PIO Core Call Error: "Platform Manager: ch32v@1.1.0+sha.40b43b1 is already installed\r\nTool Manager: Installing git+https://github.com/Community-PIO-CH32V/toolchain-riscv-windows.git\r\ngit version 2.36.1.windows.1\n\n\nCloning into 'C:\\Users\\Attiq\\.platformio\\.cache\\tmp\\pkg-installing-aky40fqp'...\nerror: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)\nerror: 7878 bytes of body are still expected\nfetch-pack: unexpected disconnect while reading sideband packet\nfatal: early EOF\nfatal: fetch-pack: invalid index-pack output\nVCSBaseException: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', 'https://github.com/Community-PIO-CH32V/toolchain-riscv-windows.git', 'C:\\\\Users\\\\Attiq\\\\.platformio\\\\.cache\\\\tmp\\\\pkg-installing-aky40fqp']"

**Comment by maxgerhardt** [comment] 2024-01-31 17:31
I cannot reproduce this error, my `git` can clone the repo just fine.

```
C:\Users\Max\temp\clone_test>git --version
git version 2.38.1.windows.1
C:\Users\Max\temp\clone_test>git clone https://github.com/Community-PIO-CH32V/toolchain-riscv-windows.git
Cloning into 'toolchain-riscv-windows'...
remote: Enumerating objects: 2215, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 2215 (delta 2), reused 6 (delta 2), pack-reused 2209
Receiving objects: 100% (2215/2215), 127.50 MiB | 7.72 MiB/s, done.
Resolving deltas: 100% (867/867), done.
Updating files: 100% (2776/2776), done.
```

Please check for internet problems on your side or update to the newest Git client. Your version 2.36.1 is behind a bit.

**Comment by maxgerhardt** [comment] 2024-02-17 23:39
Closing since unreproducable for me.

**Closed as completed by maxgerhardt** 2024-02-17 23:39 UTC
Labels: question
